### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by CyberSecGuy** [kahunalu/pwnbin#1]
Would there be a way to search instead of just keywords, but phrases as well? ie: 
-k "Something super specific goes here","another specific thing","token"

Awesome script!

**Comment by kahunalu** [comment]
For you my friend, anything! I've just put it in, let me know if it doesn't work out for you and I'll have another look. Use the option exactly as before but for sub-strings place quotes around them.

-k "Hello World","example string 2",password

Cheers!
