### ISSUE TITLE
[Low Priority]Contact

### ISSUE THREAD

**Issue by campuscodi** [kahunalu/pwnbin#2]
Hi,

Could you provide me with a way to contact you, or contact me via the email on my GitHub profile.

It's about an press article regarding pwnbin.

Also, feel free to delete this issue since it's quite off-topic.

**Comment by kahunalu** [comment]
Hey!

I've sent you an email through our reddit pm's, feel free to contact me at luke.patrick.mclaren@gmail.com

Regards,
Luke Mclaren
