### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by peasead** [kahunalu/pwnbin#3]
I'm getting the following error:

```
$ python pwnbin.py -k test -o test.log

Crawling http://pastebin.com Press ctrl+c to save file to test.log
Traceback (most recent call last):
  File "pwnbin.py", line 152, in <module>
    main(sys.argv[1:])
  File "pwnbin.py", line 28, in main
    for paste in find_new_pastes(root_html):
  File "pwnbin.py", line 96, in find_new_pastes
    ul = div.find('ul', {'class': 'right_menu'})
AttributeError: 'NoneType' object has no attribute 'find'
```

I checked all of the dependencies and I think that I have all of the dependencies listed in the import table. 

I searched what `AttributeError: 'NoneType' object has no attribute 'find'` means and it, according to stackoverflow:
"NoneType means that instead of an instance of whatever Class or Object you think you're working with, you've actually got None. That usually means that an assignment or function call up above failed or returned an unexpected result."

Any guidance here?

Thanks in advance.

**Comment by kahunalu** [comment]
Hey thanks for checking my project out! It appears that you don't have beautifulsoup installed, try running:

```
      pip install beautifulsoup4
```

If that doesn't work I'll be adding an installation tutorial to the README today and check that out to get setup, Cheers!

**Comment by peasead** [comment]
Thanks for the quick response, sadly, I do have beautifulsoup4 installed.

```
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /Library/Python/2.7/site-packages
```

Again, thanks for the help and I'll wait for the README

**Comment by peasead** [comment]
This is a requirement issue somewhere. I did it on my other system with no issue.

Closing this because I'm the problem :(

**Comment by kahunalu** [comment]
Hey thanks!

Ive been kinda busy but I was able to recreate the issue, it seems to be something with urllib2. Might be a python version issue!

Regards, 

Luke McLaren
