### ISSUE TITLE
Pastebin  blocked my IP

### ISSUE THREAD

**Issue by diehard111** [kahunalu/pwnbin#7]
Hello Kahunalu, 

After 2-3 minutes searching for a specific word or words using pwnbin , pastebin is blocking my IP .
I have an API key , can you please tell me if there is a way to use it on your script in order to avoid getting blocked ?

Thanks in advance.

**Comment by tperich** [comment]
@diehard111 The script must be refactored if not completely rewritten in order to support the API. If you're looking for a script that already uses the API, I'd recommend [PasteHunter](https://github.com/kevthehermit/PasteHunter/) which uses YARA rules for scraping data.

**Comment by diehard111** [comment]
thank you m8
